// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObatAPI.Data;

#nullable disable

namespace ObatAPI.Migrations
{
    [DbContext(typeof(ObatDbContext))]
    partial class ObatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ObatAPI.Models.Obat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("Kategori")
                        .HasColumnType("VARCHAR(100)")
                        .HasDefaultValue("Tablet")
                        .HasColumnName("kategori");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("nama");

                    b.Property<decimal>("Harga")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("harga");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("expired_date");

                    b.Property<int>("Stok")
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stok");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_created_at");

                    b.HasIndex("ExpiredDate")
                        .HasDatabaseName("idx_expired_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_status");

                    b.ToTable("obat", (string)null);
                });

            modelBuilder.Entity("ObatAPI.Models.Transaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("NoStruk")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("no_struk");

                    b.Property<decimal>("NominalDiskon")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("nominal_diskon");

                    b.Property<decimal>("NominalPajak")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("nominal_pajak");

                    b.Property<decimal>("PersentaseDiskon")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("persentase_diskon");

                    b.Property<decimal>("PersentasePajak")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("persentase_pajak");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<DateTime>("TanggalTransaksi")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tanggal_transaksi");

                    b.Property<decimal>("TotalAkhir")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_akhir");

                    b.Property<decimal>("UangBayar")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("uang_bayar");

                    b.Property<decimal>("UangKembalian")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("uang_kembalian");

                    b.HasKey("Id");

                    b.ToTable("transaksi", (string)null);
                });

            modelBuilder.Entity("ObatAPI.Models.TransaksiDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int")
                        .HasColumnName("jumlah");

                    b.Property<int>("ObatId")
                        .HasColumnType("int")
                        .HasColumnName("obat_id");

                    b.Property<decimal>("HargaSatuan")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("harga_satuan");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("TransaksiId")
                        .HasColumnType("int")
                        .HasColumnName("transaksi_id");

                    b.HasKey("Id");

                    b.HasIndex("ObatId")
                        .HasDatabaseName("IX_transaksi_detail_obat_id");

                    b.HasIndex("TransaksiId")
                        .HasDatabaseName("IX_transaksi_detail_transaksi_id");

                    b.ToTable("transaksi_detail", (string)null);
                });

            modelBuilder.Entity("ObatAPI.Models.TransaksiDetail", b =>
                {
                    b.HasOne("ObatAPI.Models.Obat", "Obat")
                        .WithMany()
                        .HasForeignKey("ObatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ObatAPI.Models.Transaksi", "Transaksi")
                        .WithMany("DetailList")
                        .HasForeignKey("TransaksiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Obat");

                    b.Navigation("Transaksi");
                });

            modelBuilder.Entity("ObatAPI.Models.Transaksi", b =>
                {
                    b.Navigation("DetailList");
                });
#pragma warning restore 612, 618
        }
    }
}
